CREATE TABLE IF NOT EXISTS COMPRA(
	IDCOMPRA SERIAL PRIMARY KEY,
	IDPRODUTO INT,
	IDPESSOA INT,
	DATACOMPRA DATE,
	CONSTRAINT FK_PESSOA_COMPRA FOREIGN KEY(IDPESSOA) REFERENCES PESSOA(IDPESSOA),
	CONSTRAINT FK_PRODUTO_COMPRA FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);
